# About the numpy random package
[Numpy](http://www.numpy.org/) is a numerical package for Python. It has a subpackage called [random](https://docs.scipy.org/doc/numpy/reference/routines.random.html). This will be the main focus of this Jupyter Notebook.

## Table Of Contents
-  [Simple Random Data](#SimpleRandomData)
    -  [random.rand](#random.rand)
    -  [random.randn](#random.randn)
    -  [random.randint](#random.randint)    
    -  [random.random_integers](#random.random_integers)
    -  [random.random_sample](#random.random_sample)
    -  [random.random](#random.random)
    -  [random.ranf](#random.ranf)
    -  [random.sample](#random.sample)
    -  [random.choice](#random.choice)
    -  [random.bytes](#random.bytes)
-  [Permutations](#Permutations)
    -  [random.shuffle](#random.shuffle)
    -  [random.permutation](#random.permutation)
-  [Distributions](#Distributions)
    -  [random.beta](#random.beta)
    -  [random.binomial](#random.binomial)
    -  [random.chisquare](#random.chisquare)
    -  [random.dirichlet](#random.dirichlet)
    -  [random.exponential](#random.exponential)
    -  [random.f](#random.f)
    -  [random.gamma](#random.gamma)
    -  [random.geometric](#random.geometric)
    -  [random.gumbel](#random.gumbel)
    -  [random.hypergeometric](#random.hypergeometric)
    -  [random.laplace](#random.laplace)
    -  [random.logistic](#random.logistic)
    -  [random.lognormal](#random.lognormal)
    -  [random.logseries](#random.logseries)
    -  [random.multinomial](#random.multinomial)
    -  [random.multivariate_normal](#random.multivariate_normal)
    -  [random.negative_binomial](#random.negative_binomial)
    -  [random.noncentral_chisquare](#random.noncentral_chisquare)
    -  [random.noncentral_f](#random.noncentral_f)
    -  [random.normal](#random.normal)
    -  [random.pareto](#random.pareto)
    -  [random.poisson](#random.poisson)
    -  [random.power](#random.power)
    -  [random.rayleigh](#random.rayleigh)
    -  [random.standard_cauchy](#random.standard_cauchy)
    -  [random.standard_exponential](#random.standard_exponential)
    -  [random.standard_gamma](#random.standard_gamma)
    -  [random.standard_normal](#random.standard_normal)
    -  [random.standard_t](#random.standard_t)
    -  [random.triangular](#random.triangular)
    -  [random.uniform](#random.uniform)
    -  [random.vonmises](#random.vonmises)
    -  [random.wald](#random.wald)
    -  [random.weibull](#random.weibull)
    -  [random.zipf](#random.zipf)
-  [Random generator](#RandomGenerator)
    -  [random.RandomState](#random.RandomState)
    -  [random.seed](#random.seed)
    -  [random.get_state](#random.get_state)
    -  [random.set_state](#random.set_state)

In [1]:
import numpy as np

The numpy namespace includes all names under the numpy.core and numpy.lib namespaces as well. This numpy import will
also import the names from numpy.core and numpy.lib. This is the recommended way to use numpy.

<a id="SimpleRandomData"></a>
## Simple random data

### random.rand

In [11]:
np.random.rand(4,5)

array([[0.97466704, 0.73913696, 0.93639684, 0.16050302, 0.78594667],
       [0.27178007, 0.33086439, 0.02885348, 0.68974743, 0.1332771 ],
       [0.61442726, 0.6506748 , 0.98035923, 0.54584876, 0.05924927],
       [0.1967879 , 0.03080955, 0.53516522, 0.59527295, 0.87016017]])

The above random.rand(*n*, *n*) outputs an array in the given shape, and popuates the array with random samples from a uniform distribution over [0, 1].

In [15]:
np.random.rand(5)

array([0.50075858, 0.45725415, 0.49696726, 0.30479839, 0.31177037])

The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.

In [13]:
np.random.rand()

0.5523263446760002

If an interface that takes a shape-tuple as the first argument is needed refer to the [random.random_sample()](#random.random_sample) below.

### random.randn

In [67]:
np.random.randn(3,4)

array([[-0.6785402 , -2.0488449 , -0.6027356 , -0.89845715],
       [ 0.31768301,  0.03052133, -0.32097442,  0.95287772],
       [ 0.43406763,  0.70817339,  0.32089425,  0.78813425]])

The above random.randn(*n*, *n*) returns a random sample (or samples) if positive, randn generates an array of a shape using the parameters provided. If parameters are specified an array is filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1, if any are floats, they are first converted to integers by truncation. 

If an interface that takes a tuple as the first argument is needed refer to [random.standard_normal](#random.standard_normal) outlined below.

In [68]:
np.random.randn(3)

array([ 0.30440809,  1.00882387, -0.28595761])

A single float randomly sampled from the distribution is returned if no argument is provided.

In [69]:
np.random.randn()

-1.0890890959075223

### random.randint

### random.random_integers

### random.random_sample

### random.random

### random.ranf

### random.sample

### random.choice

### random.bytes

## Permutations

### random.shuffle

### random.permutation

## Distributions

### random.beta

### random.binomial

### random.chisquare

### random.dirichlet

### random.exponential

### random.f

### random.gamma

### random.geometric

### random.gumbel

### random.hypergeometric

### random.laplace

### random.logistic

### random.lognormal

### random.logseries

### random.multinomial

### random.multivariate_normal

### random.negative_binomial

### random.noncentral_chisquare

### random.noncentral_f

### random.normal

### random.pareto

### random.poisson

### random.power

### random.rayleigh

### random.standard_cauchy

### random.standard_exponential

### random.standard_gamma

### random.standard_normal

### random.standard_t

### random.triangular

### random.uniform

### random.vonmises

### random.wald

### random.weibull

### random.zipf

<a id="RandomGenerator"></a>
## Random generator

### random.RandomState

### random.seed

### random.get_state

### random.set_state

### random.random_sample

### random.standard_normal

In [2]:
np.random.uniform(0.0, 10.0)

4.757653517247865

In [5]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

When using the .arange() and .reshape() together the parameters of the .reshape() method must multiply to equal the parameter of the .arange() method.