# About the numpy random package
[Numpy](http://www.numpy.org/) is a numerical package for Python. It has a subpackage called [random](https://docs.scipy.org/doc/numpy/reference/routines.random.html). This will be the main focus of this Jupyter Notebook.

## Table Of Contents
-  [Simple Random Data](#SimpleRandomData)
    -  [random.rand](#random.rand)
    -  [random.randn](#random.randn)
    -  [random.randint](#random.randint)    
    -  [random.random_integers](#random.random_integers)
    -  [random.random_sample](#random.random_sample)
    -  [random.random](#random.random)
    -  [random.ranf](#random.ranf)
    -  [random.sample](#random.sample)
    -  [random.choice](#random.choice)
    -  [random.bytes](#random.bytes)
-  [Permutations](#Permutations)
    -  [random.shuffle](#random.shuffle)
    -  [random.permutation](#random.permutation)
-  [Distributions](#Distributions)
    -  [random.beta](#random.beta)
    -  [random.binomial](#random.binomial)
    -  [random.chisquare](#random.chisquare)
    -  [random.dirichlet](#random.dirichlet)
    -  [random.exponential](#random.exponential)
    -  [random.f](#random.f)
    -  [random.gamma](#random.gamma)
    -  [random.geometric](#random.geometric)
    -  [random.gumbel](#random.gumbel)
    -  [random.hypergeometric](#random.hypergeometric)
    -  [random.laplace](#random.laplace)
    -  [random.logistic](#random.logistic)
    -  [random.lognormal](#random.lognormal)
    -  [random.logseries](#random.logseries)
    -  [random.multinomial](#random.multinomial)
    -  [random.multivariate_normal](#random.multivariate_normal)
    -  [random.negative_binomial](#random.negative_binomial)
    -  [random.noncentral_chisquare](#random.noncentral_chisquare)
    -  [random.noncentral_f](#random.noncentral_f)
    -  [random.normal](#random.normal)
    -  [random.pareto](#random.pareto)
    -  [random.poisson](#random.poisson)
    -  [random.power](#random.power)
    -  [random.rayleigh](#random.rayleigh)
    -  [random.standard_cauchy](#random.standard_cauchy)
    -  [random.standard_exponential](#random.standard_exponential)
    -  [random.standard_gamma](#random.standard_gamma)
    -  [random.standard_normal](#random.standard_normal)
    -  [random.standard_t](#random.standard_t)
    -  [random.triangular](#random.triangular)
    -  [random.uniform](#random.uniform)
    -  [random.vonmises](#random.vonmises)
    -  [random.wald](#random.wald)
    -  [random.weibull](#random.weibull)
    -  [random.zipf](#random.zipf)
-  [Random generator](#RandomGenerator)
    -  [random.RandomState](#random.RandomState)
    -  [random.seed](#random.seed)
    -  [random.get_state](#random.get_state)
    -  [random.set_state](#random.set_state)

In [1]:
import numpy as np

The numpy namespace includes all names under the numpy.core and numpy.lib namespaces as well. This numpy import will
also import the names from numpy.core and numpy.lib. This is the recommended way to use numpy.

<a id="SimpleRandomData"></a>
## Simple random data

### random.rand

In [2]:
np.random.rand(4,5)

array([[0.69859891, 0.82105421, 0.83563145, 0.86313532, 0.8681074 ],
       [0.35543156, 0.85069763, 0.15465084, 0.70850477, 0.5379304 ],
       [0.66016757, 0.26948782, 0.20154825, 0.60181168, 0.62859585],
       [0.70739193, 0.59859371, 0.37930076, 0.98622533, 0.97014319]])

The above random.rand(*n*, *n*) outputs an array in the given shape, and popuates the array with random samples from a uniform distribution over [0, 1].

In [3]:
np.random.rand(5)

array([0.0715946 , 0.39037232, 0.20486413, 0.71736807, 0.14966425])

The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.

In [4]:
np.random.rand()

0.811013382352825

If an interface that takes a shape-tuple as the first argument is needed refer to the [random.random_sample()](#random.random_sample) below.

### random.randn

In [5]:
np.random.randn(3,4)

array([[ 0.04192056, -0.25229185, -1.08163189,  0.62934784],
       [-1.09841838, -0.30434348, -1.16162332, -0.33876878],
       [ 0.8762825 ,  0.16036543,  0.33313283,  0.89210084]])

The above random.randn(*n*, *n*) returns a random sample (or samples) if positive, randn generates an array of a shape using the parameters provided. If parameters are specified an array is filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1, if any are floats, they are first converted to integers by truncation. 

If an interface that takes a tuple as the first argument is needed refer to [random.standard_normal](#random.standard_normal) outlined below.

In [6]:
np.random.randn(3)

array([-0.68664212,  2.29406867, -0.60451929])

A single float randomly sampled from the distribution is returned if no argument is provided.

In [7]:
np.random.randn()

-0.2986526887196061

For random samples from normal distribution, with mean vector μ and standard deviation σ, use: 
N(μ, σ ^2)

Which is implemented as follows:

In [8]:
np.random.randn(2, 5) + 7

array([[ 7.55433192,  7.60719705,  7.39262193,  4.78480788, 10.43970821],
       [ 6.72927271,  6.7083807 ,  6.50951456,  6.63340051,  7.22300376]])

### random.randint

This method returns random integers from low (inclusive) to high (exclusive).

The parameters are as follows:

low (int):<br>The lowest int to be drawn from the distribution, unless high=None, this parameter is one above the highest such integer.

In [16]:
np.random.randint(3)

2

high (int, optional):<br>If specified, one above the largest signed integer to be drawn from the distribution.

In [153]:
np.random.randint(4, high=10)

4

size (int or tuple of ints, optional):<br>Default is none which returns a single value, if specified defines the output shape.

In [17]:
np.random.randint(2, size=7)

array([1, 1, 1, 1, 0, 1, 1])

dtype (dtype, optional):<br>Desired data type object of the result.

In [101]:
np.random.randint(2.0, high=4, size=(3,2), dtype='int_')

array([[3, 3],
       [3, 3],
       [3, 2]])

This method returns an int or array of ints, depending on if the size is specified.

### random.random_integers

Random integers of type np.int between low and high, inclusive.

This function has been deprecated. Use [randint](#random.randint) instead.
Deprecated since version 1.11.0.

### random.random_sample

This method returns a random float (floats) in the half-open interval [0.0, 1.0]. Half-open interval is a set of numbers between two given numbers but including only one endpoint.

Only has one optional parameter:
size (int or tuple of ints, optional):
If specified, outputs the given shape.

Returns a float or an array of floats.

In [155]:
np.random.random_sample()

0.01850309690013674

In [326]:
np.random.random_sample(3)

array([0.07566434, 0.06322685, 0.76972189])

In [158]:
np.random.random_sample((3, 3))

array([[0.36985564, 0.51377121, 0.11322012],
       [0.3079192 , 0.49808738, 0.50008529],
       [0.08631312, 0.47953271, 0.12128217]])

### random.random

This method is an alias to [random.random_sample](#random.random_sample).

Proof in code:

In [159]:
np.random.random is np.random.random_sample

True

### random.ranf

This method is an alias to [random.random_sample](#random.random_sample)

Proof in code:

In [160]:
np.random.ranf is np.random.random_sample

True

### random.sample

This method is an alias to [random.random_sample](#random.random_sample)

Proof in code:

In [161]:
np.random.sample is np.random.random_sample

True

### random.choice

This method generates a random sample from a given 1-D array.

The parameters it takes are as follows:

a (1-D array-like or int):<br>If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if a were np.arange(a)

size (int or tuple of ints, optional):<br>Defines the output shape, the default is None, in which case a single value is returned.

replace (boolean, optional):<br>Whether the sample is with or without replacement

p (1-D array-like, optional):<br>The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution over all entries in a.

This method returns a single item or an array of random samples.

In [182]:
np.random.choice(3)

2

Generate a uniform random sample from np.arange(3) of size 5:

In [175]:
np.random.choice(3, 5)

array([1, 2, 1, 2, 0])

Generate a non-uniform random sample from np.arange(3) of size 4:

In [186]:
np.random.choice(3, 4, p=[0.2, 0.1, 0.7])

array([2, 2, 0, 2], dtype=int64)

Generate a uniform sample from np.arange(4) of size 3 with replacement:

In [253]:
np.random.choice(3, 4, replace=True)

array([1, 2, 1, 0])

Any of the above can be repeated with an arbitrary array. For example:

In [255]:
pet_array = ['rabbit', 'dog', 'cat', 'lizard', 'snake', 'goldfish']
np.random.choice(pet_array, 3, p=[0.1, 0.1, 0.1, 0.4, 0.2, 0.1])

array(['cat', 'lizard', 'goldfish'], dtype='<U8')

### random.bytes

This method returns random bytes.

It takes one parameter, length, which determines the number of random bytes.

It returns a String of length *length*.

In [325]:
np.random.bytes(100)

b'\x9aF\x0b^Fh\x12\x11\x18lB\xc03}\x00\x9f\x98}\x86")\xf0\x83\xd1\xfb\x92Z\x18\xb22\xa3Z\x06\xa0\x95qQ\xa2\xbf21\xc23-\xc4\x98\xdeV\x14\x91@<\x87=\xb2pr\xc8\xf4\x14n\xefm\x8c\x04ic\x8f\x8ch\xdb\xf4\x17\xa9J\xb7I5u_D\xba\x11`\x97\xfb\xde\x9b\x88\x06\xac\xe7e\xd3\xd2z\xbb\x1e\x9b\xe7'

## Permutations

### random.shuffle

### random.permutation

## Distributions

### random.beta

### random.binomial

### random.chisquare

### random.dirichlet

### random.exponential

### random.f

### random.gamma

### random.geometric

### random.gumbel

### random.hypergeometric

### random.laplace

### random.logistic

### random.lognormal

### random.logseries

### random.multinomial

### random.multivariate_normal

### random.negative_binomial

### random.noncentral_chisquare

### random.noncentral_f

### random.normal

### random.pareto

### random.poisson

### random.power

### random.rayleigh

### random.standard_cauchy

### random.standard_exponential

### random.standard_gamma

### random.standard_normal

### random.standard_t

### random.triangular

### random.uniform

### random.vonmises

### random.wald

### random.weibull

### random.zipf

<a id="RandomGenerator"></a>
## Random generator

### random.RandomState

### random.seed

### random.get_state

### random.set_state

### random.random_sample

### random.standard_normal

In [9]:
np.random.uniform(0.0, 10.0)

5.587716443563135

In [10]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

When using the .arange() and .reshape() together the parameters of the .reshape() method must multiply to equal the parameter of the .arange() method.