# About the numpy random package
[Numpy](http://www.numpy.org/) is a numerical package for Python. It has a subpackage called [random](https://docs.scipy.org/doc/numpy/reference/routines.random.html). This will be the main focus of this Jupyter Notebook.

## Table Of Contents
-  [Simple Random Data](#SimpleRandomData)
    -  [random.rand](#random.rand)
    -  [random.randn](#random.randn)
    -  [random.randint](#random.randint)    
    -  [random.random_integers](#random.random_integers)
    -  [random.random_sample](#random.random_sample)
    -  [random.random](#random.random)
    -  [random.ranf](#random.ranf)
    -  [random.sample](#random.sample)
    -  [random.choice](#random.choice)
    -  [random.bytes](#random.bytes)
-  [Permutations](#Permutations)
    -  [random.shuffle](#random.shuffle)
    -  [random.permutation](#random.permutation)
-  [Distributions](#Distributions)
    -  [random.beta](#random.beta)
    -  [random.binomial](#random.binomial)
    -  [random.chisquare](#random.chisquare)
    -  [random.dirichlet](#random.dirichlet)
    -  [random.exponential](#random.exponential)
    -  [random.f](#random.f)
    -  [random.gamma](#random.gamma)
    -  [random.geometric](#random.geometric)
    -  [random.gumbel](#random.gumbel)
    -  [random.hypergeometric](#random.hypergeometric)
    -  [random.laplace](#random.laplace)
    -  [random.logistic](#random.logistic)
    -  [random.lognormal](#random.lognormal)
    -  [random.logseries](#random.logseries)
    -  [random.multinomial](#random.multinomial)
    -  [random.multivariate_normal](#random.multivariate_normal)
    -  [random.negative_binomial](#random.negative_binomial)
    -  [random.noncentral_chisquare](#random.noncentral_chisquare)
    -  [random.noncentral_f](#random.noncentral_f)
    -  [random.normal](#random.normal)
    -  [random.pareto](#random.pareto)
    -  [random.poisson](#random.poisson)
    -  [random.power](#random.power)
    -  [random.rayleigh](#random.rayleigh)
    -  [random.standard_cauchy](#random.standard_cauchy)
    -  [random.standard_exponential](#random.standard_exponential)
    -  [random.standard_gamma](#random.standard_gamma)
    -  [random.standard_normal](#random.standard_normal)
    -  [random.standard_t](#random.standard_t)
    -  [random.triangular](#random.triangular)
    -  [random.uniform](#random.uniform)
    -  [random.vonmises](#random.vonmises)
    -  [random.wald](#random.wald)
    -  [random.weibull](#random.weibull)
    -  [random.zipf](#random.zipf)
-  [Random generator](#RandomGenerator)
    -  [random.RandomState](#random.RandomState)
    -  [random.seed](#random.seed)
    -  [random.get_state](#random.get_state)
    -  [random.set_state](#random.set_state)

In [1]:
import numpy as np

The numpy namespace includes all names under the numpy.core and numpy.lib namespaces as well. This numpy import will
also import the names from numpy.core and numpy.lib. This is the recommended way to use numpy.

<a id="SimpleRandomData"></a>
## Simple random data

### random.rand

In [2]:
np.random.rand(4,5)

array([[0.36318136, 0.17037968, 0.59026796, 0.73604686, 0.02361892],
       [0.88219362, 0.70934464, 0.52074618, 0.78820397, 0.57740095],
       [0.65956035, 0.38859828, 0.96011082, 0.44264497, 0.34529522],
       [0.44806548, 0.69769817, 0.69166249, 0.38715653, 0.43869397]])

The above random.rand(*n*, *n*) outputs an array in the given shape, and popuates the array with random samples from a uniform distribution over [0, 1].

In [3]:
np.random.rand(5)

array([0.46434452, 0.05254348, 0.27678362, 0.99042007, 0.8781476 ])

The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.

In [4]:
np.random.rand()

0.4025732628461596

If an interface that takes a shape-tuple as the first argument is needed refer to the [random.random_sample()](#random.random_sample) below.

### random.randn

In [5]:
np.random.randn(3,4)

array([[-0.75700478,  1.08315378, -1.68039744, -0.01892834],
       [ 0.7665825 ,  0.38713854, -1.00143517, -2.73466325],
       [-0.43055843,  0.11921046,  0.30087898,  0.92578746]])

The above random.randn(*n*, *n*) returns a random sample (or samples) if positive, randn generates an array of a shape using the parameters provided. If parameters are specified an array is filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1, if any are floats, they are first converted to integers by truncation. 

If an interface that takes a tuple as the first argument is needed refer to [random.standard_normal](#random.standard_normal) outlined below.

In [6]:
np.random.randn(3)

array([-0.71690856,  0.28792799, -1.41312205])

A single float randomly sampled from the distribution is returned if no argument is provided.

In [7]:
np.random.randn()

-1.0672951099711945

For random samples from normal distribution, with mean vector μ and standard deviation σ, use: 
N(μ, σ ^2)

Which is implemented as follows:

In [8]:
np.random.randn(2, 5) + 7

array([[6.93674527, 9.19881884, 8.12909969, 5.91668203, 6.30284703],
       [7.09043478, 6.2024257 , 7.16019301, 6.26251615, 8.07694555]])

### random.randint

This function returns random integers from low (inclusive) to high (exclusive).

The parameters are as follows:

low (int):<br>The lowest int to be drawn from the distribution, unless high=None, this parameter is one above the highest such integer.

In [9]:
np.random.randint(3)

1

high (int, optional):<br>If specified, one above the largest signed integer to be drawn from the distribution.

In [10]:
np.random.randint(4, high=10)

6

size (int or tuple of ints, optional):<br>Default is none which returns a single value, if specified defines the output shape.

In [11]:
np.random.randint(2, size=7)

array([0, 0, 0, 1, 1, 0, 0])

dtype (dtype, optional):<br>Desired data type object of the result.

In [12]:
np.random.randint(2.0, high=4, size=(3,2), dtype='int_')

array([[3, 3],
       [2, 3],
       [2, 3]])

This function returns an int or array of ints, depending on if the size is specified.

### random.random_integers

Random integers of type np.int between low and high, inclusive.

This function has been deprecated. Use [randint](#random.randint) instead.
Deprecated since version 1.11.0.

### random.random_sample

This function returns a random float (floats) in the half-open interval [0.0, 1.0]. Half-open interval is a set of numbers between two given numbers but including only one endpoint.

Only has one optional parameter:
size (int or tuple of ints, optional):
If specified, outputs the given shape.

Returns a float or an array of floats.

In [13]:
np.random.random_sample()

0.7530901810653257

In [14]:
np.random.random_sample(3)

array([0.18478368, 0.75358217, 0.56197531])

In [15]:
np.random.random_sample((3, 3))

array([[0.3358384 , 0.73130858, 0.82372217],
       [0.77744651, 0.06042339, 0.44597659],
       [0.02970275, 0.39728522, 0.20875337]])

### random.random

This function is an alias to [random.random_sample](#random.random_sample).

Proof in code:

In [16]:
np.random.random is np.random.random_sample

True

### random.ranf

This function is an alias to [random.random_sample](#random.random_sample)

Proof in code:

In [17]:
np.random.ranf is np.random.random_sample

True

### random.sample

This function is an alias to [random.random_sample](#random.random_sample)

Proof in code:

In [18]:
np.random.sample is np.random.random_sample

True

### random.choice

This function generates a random sample from a given 1-D array.

The parameters it takes are as follows:

a (1-D array-like or int):<br>If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if a were np.arange(a)

size (int or tuple of ints, optional):<br>Defines the output shape, the default is None, in which case a single value is returned.

replace (boolean, optional):<br>Whether the sample is with or without replacement

p (1-D array-like, optional):<br>The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution over all entries in a.

This function returns a single item or an array of random samples.

In [19]:
np.random.choice(3)

0

Generate a uniform random sample from np.arange(3) of size 5:

In [20]:
np.random.choice(3, 5)

array([2, 0, 0, 1, 0])

Generate a non-uniform random sample from np.arange(3) of size 4:

In [21]:
np.random.choice(3, 4, p=[0.2, 0.1, 0.7])

array([2, 2, 2, 2], dtype=int64)

Generate a uniform sample from np.arange(4) of size 3 with replacement:

In [22]:
np.random.choice(3, 4, replace=True)

array([2, 0, 0, 1])

Any of the above can be repeated with an arbitrary array. For example:

In [23]:
pet_array = ['rabbit', 'dog', 'cat', 'lizard', 'snake', 'goldfish']
np.random.choice(pet_array, 3, p=[0.1, 0.1, 0.1, 0.4, 0.2, 0.1])

array(['lizard', 'snake', 'dog'], dtype='<U8')

### random.bytes

This function returns random bytes.

It takes one parameter, length, which determines the number of random bytes.

It returns a String of length *length*.

In [24]:
np.random.bytes(100)

b'\xdb\x1fp^\x14\xfeL\xa9\x9fV\xcaT\rpAV\xf6y\x05\x18\xb5\x8a\xd7@]\xbe\x93+Mt\x85P=v\r\x8a\x9ct\xbe\xc1\xaf\xe8\xeaVJ\x15\xd6\x11\\r\x01\x14\xb1\x1ap\x97\x85\xf14\xd7g\xb0\xad\xe0\xb4\x07~X=\x80$h\xe9\x15"\xf5\xe3\xedT\xf9\x1b0\x8bS\x8c%C>\xee\xaa\xff\xf8\xe1f$\x11\xea\xd4u\x9f'

## Permutations

### random.shuffle

This function is used to modify a sequesnce in-place by shuffling its contents.

In [29]:
colour_array = ["Black", "Blue", "Red", "Green", "Yellow"]
np.random.shuffle(colour_array)
colour_array

['Black', 'Blue', 'Yellow', 'Green', 'Red']

This function only shuffles the array along the first axis of a multi-dimensional array, the order of sub-arrays are changed but contents remain the same.

In [77]:
array = np.arange(15).reshape((3, 5))
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
np.random.shuffle(array)
array

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

### random.permutation

This function randomly permutes a sequence, or returns a permuted range.

This method takes one parameter, which can be either be an int or an array.
If an int, randomly permute *np.arange(int)*.
If an array, make a copy and shuffle the elements randomly.

In [80]:
np.random.permutation(10)

array([0, 2, 7, 3, 6, 9, 5, 4, 1, 8])

In [84]:
array = np.arange(15).reshape((3, 5))
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [106]:
np.random.permutation(array)

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

## Distributions

### random.beta

This function is used to draw samples from a Beta distribution. The Beta distribution is a special case of the Dirichlet distribution, and is related to the Gamma distribution.<br><br>
This function can take three parameters:
<br>a (float or array of floats):
Alpha, must be a positive value.<br>b (float or array of floats):
Beta, must be a positive value.<br>size (int or tuple of ints, optional):
Defines the output shape. If size=None (default), a single value is returned if a and b are both scalars. Otherwise, np.broadcast(a, b).size samples are drawn.

In [107]:
np.random.beta(2.1, 5.3)

0.21130959446868164

In [108]:
np.random.beta(2.4, 4.5, 5)

array([0.26024536, 0.62359122, 0.55681808, 0.56948957, 0.24230463])

### random.binomial

This function is used to draw samples from a binomial distribution.

Samples are drawn with specified parameters, n trials and p probability of success where n an integer >= 0 and p is in the interval [0,1]. (n may be input as a float, but it is truncated to an integer in use)

This function takes the following parameters:	
n (int or array_like of ints):<br>
Must be >= 0. Floats are also accepted, but they will be truncated to integers.<br>
p (float or array_like of floats):<br>
Must be between 0 and 1 inclusive.<br>
size (int or tuple of ints, optional):<br>
Defines the output shape. If size is None (default), a single value is returned if n and p are both scalars. Otherwise, np.broadcast(n, p).size samples are drawn.

This function returns an *n* dimensional array or scalar.

Draw samples from the distribution:

In [113]:
n, p = 10, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, 100)
# result of flipping a coin 10 times, tested 100 times.
s

array([4, 4, 3, 8, 6, 5, 7, 2, 5, 4, 6, 6, 7, 2, 6, 5, 5, 5, 7, 6, 9, 5,
       6, 5, 4, 5, 4, 4, 4, 6, 5, 6, 5, 7, 3, 5, 2, 4, 9, 5, 3, 6, 4, 6,
       6, 8, 6, 7, 5, 5, 5, 5, 3, 6, 6, 5, 5, 2, 7, 6, 5, 7, 7, 2, 6, 8,
       5, 3, 6, 6, 6, 5, 2, 5, 5, 5, 6, 4, 3, 5, 2, 5, 2, 8, 3, 4, 2, 6,
       6, 5, 5, 6, 6, 8, 6, 4, 6, 4, 7, 7])

### random.chisquare

This function is used to draw samples from a chi-square distribution.

Independent random variables, each with standard normal distributions (mean 0, variance 1), are squared and summed, the resulting distribution is chi-square. This distribution is often used in hypothesis testing.
    
This function takes the following parameters:	

df (float or array_like of floats):<br>
Number of degrees of freedom, should be > 0.<br>
size (int or tuple of ints, optional):<br>
Defines the output shape. If size is None (default), a single value is returned if df is a scalar. Otherwise, np.array(df).size samples are drawn.

This function returns an *n* dimensional array or scalar.

In [114]:
np.random.chisquare(2,4)

array([0.70255726, 4.45202563, 0.40829309, 2.9825124 ])

### random.dirichlet

This function is used to draw samples from the Dirichlet distribution.

A Dirichlet-distributed random variable can be seen as a multivariate generalization of a Beta distribution. Dirichlet pdf is the conjugate prior of a multinomial in Bayesian inference.
    
This function takes the following parameters:	

alpha (array):<br>
Parameter of the distribution (k dimension for sample of dimension k).<br>
size (int or tuple of ints, optional):
Defines the output shape. Default is None, in which case a single value is returned.

This function returns an *n* dimensional array.	

In [119]:
s = np.random.dirichlet((10, 5, 3), 20).transpose()
s

array([[0.45757354, 0.63156503, 0.63180611, 0.52850831, 0.45129896,
        0.50120469, 0.64884622, 0.57614129, 0.58641672, 0.47293778,
        0.50121979, 0.66649591, 0.56461696, 0.59432749, 0.65688562,
        0.43883279, 0.57924584, 0.5345307 , 0.41840738, 0.73371181],
       [0.20686687, 0.20453422, 0.30405319, 0.23456431, 0.33609388,
        0.3396103 , 0.32030861, 0.12189081, 0.25038251, 0.29321016,
        0.21542393, 0.12679377, 0.42642993, 0.28703248, 0.27350939,
        0.33197222, 0.29892129, 0.23560893, 0.13331945, 0.10749088],
       [0.33555959, 0.16390075, 0.0641407 , 0.23692738, 0.21260716,
        0.159185  , 0.03084518, 0.3019679 , 0.16320077, 0.23385206,
        0.28335628, 0.20671032, 0.00895311, 0.11864003, 0.06960499,
        0.22919498, 0.12183287, 0.22986037, 0.44827317, 0.15879731]])

### random.exponential

 numpy.random.exponential(scale=1.0, size=None)

    Draw samples from an exponential distribution.
    
The exponential distribution is a continuous analogue of the geometric distribution. It describes many common situations, such as the size of raindrops measured over many rainstorms [1], or the time between page requests to Wikipedia [2].
Parameters:	

scale : float or array_like of floats

    The scale parameter, \beta = 1/\lambda.
size : int or tuple of ints, optional

    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if scale is a scalar. Otherwise, np.array(scale).size samples are drawn.

Returns:	

out : ndarray or scalar

    Drawn samples from the parameterized exponential distribution.



### random.f

 numpy.random.f(dfnum, dfden, size=None)

    Draw samples from an F distribution.

    Samples are drawn from an F distribution with specified parameters, dfnum (degrees of freedom in numerator) and dfden (degrees of freedom in denominator), where both parameters should be greater than zero.

    The random variate of the F distribution (also known as the Fisher distribution) is a continuous probability distribution that arises in ANOVA tests, and is the ratio of two chi-square variates.
    Parameters:	

    dfnum : float or array_like of floats

        Degrees of freedom in numerator, should be > 0.
    dfden : float or array_like of float

        Degrees of freedom in denominator, should be > 0.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if dfnum and dfden are both scalars. Otherwise, np.broadcast(dfnum, dfden).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized Fisher distribution.

The F statistic is used to compare in-group variances to between-group variances. Calculating the distribution depends on the sampling, and so it is a function of the respective degrees of freedom in the problem. The variable dfnum is the number of samples minus one, the between-groups degrees of freedom, while dfden is the within-groups degrees of freedom, the sum of the number of samples in each group minus the number of groups.

Glantz, Stanton A. “Primer of Biostatistics.”, McGraw-Hill, Fifth Edition, 2002.

An example from Glantz[1], pp 47-40:

Two groups, children of diabetics (25 people) and children from people without diabetes (25 controls). Fasting blood glucose was measured, case group had a mean value of 86.1, controls had a mean value of 82.2. Standard deviations were 2.09 and 2.49 respectively. Are these data consistent with the null hypothesis that the parents diabetic status does not affect their children’s blood glucose levels? Calculating the F statistic from the data gives a value of 36.01.

Draw samples from the distribution:
>>>

>>> dfnum = 1. # between group degrees of freedom
>>> dfden = 48. # within groups degrees of freedom
>>> s = np.random.f(dfnum, dfden, 1000)

The lower bound for the top 1% of the samples is :
>>>

>>> sort(s)[-10]
7.61988120985

So there is about a 1% chance that the F statistic will exceed 7.62, the measured value is 36, so the null hypothesis is rejected at the 1% level.

### random.gamma

 numpy.random.gamma(shape, scale=1.0, size=None)

    Draw samples from a Gamma distribution.

    Samples are drawn from a Gamma distribution with specified parameters, shape (sometimes designated “k”) and scale (sometimes designated “theta”), where both parameters are > 0.
    Parameters:	

    shape : float or array_like of floats

        The shape of the gamma distribution. Should be greater than zero.
    scale : float or array_like of floats, optional

        The scale of the gamma distribution. Should be greater than zero. Default is equal to 1.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if shape and scale are both scalars. Otherwise, np.broadcast(shape, scale).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized gamma distribution.

The Gamma distribution is often used to model the times to failure of electronic components, and arises naturally in processes for which the waiting times between Poisson distributed events are relevant.

Draw samples from the distribution:
>>>

>>> shape, scale = 2., 2.  # mean=4, std=2*sqrt(2)
>>> s = np.random.gamma(shape, scale, 1000)

Display the histogram of the samples, along with the probability density function:
>>>

>>> import matplotlib.pyplot as plt
>>> import scipy.special as sps
>>> count, bins, ignored = plt.hist(s, 50, density=True)
>>> y = bins**(shape-1)*(np.exp(-bins/scale) /
...                      (sps.gamma(shape)*scale**shape))
>>> plt.plot(bins, y, linewidth=2, color='r')
>>> plt.show()


### random.geometric

 numpy.random.geometric(p, size=None)

    Draw samples from the geometric distribution.

    Bernoulli trials are experiments with one of two outcomes: success or failure (an example of such an experiment is flipping a coin). The geometric distribution models the number of trials that must be run in order to achieve success. It is therefore supported on the positive integers, k = 1, 2, ....

    The probability mass function of the geometric distribution is

    f(k) = (1 - p)^{k - 1} p

    where p is the probability of success of an individual trial.
    Parameters:	

    p : float or array_like of floats

        The probability of success of an individual trial.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if p is a scalar. Otherwise, np.array(p).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized geometric distribution.

Draw ten thousand values from the geometric distribution, with the probability of an individual success equal to 0.35:
>>>

>>> z = np.random.geometric(p=0.35, size=10000)

How many trials succeeded after a single run?
>>>

>>> (z == 1).sum() / 10000.
0.34889999999999999 #random

### random.gumbel

 numpy.random.gumbel(loc=0.0, scale=1.0, size=None)

    Draw samples from a Gumbel distribution.

    Draw samples from a Gumbel distribution with specified location and scale. For more information on the Gumbel distribution, see Notes and References below.
    Parameters:	

    loc : float or array_like of floats, optional

        The location of the mode of the distribution. Default is 0.
    scale : float or array_like of floats, optional

        The scale parameter of the distribution. Default is 1.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized Gumbel distribution.

The Gumbel (or Smallest Extreme Value (SEV) or the Smallest Extreme Value Type I) distribution is one of a class of Generalized Extreme Value (GEV) distributions used in modeling extreme value problems. The Gumbel is a special case of the Extreme Value Type I distribution for maximums from distributions with “exponential-like” tails.

The Gumbel (named for German mathematician Emil Julius Gumbel) was used very early in the hydrology literature, for modeling the occurrence of flood events. It is also used for modeling maximum wind speed and rainfall rates. It is a “fat-tailed” distribution - the probability of an event in the tail of the distribution is larger than if one used a Gaussian, hence the surprisingly frequent occurrence of 100-year floods. Floods were initially modeled as a Gaussian process, which underestimated the frequency of extreme events.

It is one of a class of extreme value distributions, the Generalized Extreme Value (GEV) distributions, which also includes the Weibull and Frechet.

Draw samples from the distribution:
>>>

>>> mu, beta = 0, 0.1 # location and scale
>>> s = np.random.gumbel(mu, beta, 1000)

Display the histogram of the samples, along with the probability density function:
>>>

>>> import matplotlib.pyplot as plt
>>> count, bins, ignored = plt.hist(s, 30, density=True)
>>> plt.plot(bins, (1/beta)*np.exp(-(bins - mu)/beta)
...          * np.exp( -np.exp( -(bins - mu) /beta) ),
...          linewidth=2, color='r')
>>> plt.show()

Show how an extreme value distribution can arise from a Gaussian process and compare to a Gaussian:
>>>

>>> means = []
>>> maxima = []
>>> for i in range(0,1000) :
...    a = np.random.normal(mu, beta, 1000)
...    means.append(a.mean())
...    maxima.append(a.max())
>>> count, bins, ignored = plt.hist(maxima, 30, density=True)
>>> beta = np.std(maxima) * np.sqrt(6) / np.pi
>>> mu = np.mean(maxima) - 0.57721*beta
>>> plt.plot(bins, (1/beta)*np.exp(-(bins - mu)/beta)
...          * np.exp(-np.exp(-(bins - mu)/beta)),
...          linewidth=2, color='r')
>>> plt.plot(bins, 1/(beta * np.sqrt(2 * np.pi))
...          * np.exp(-(bins - mu)**2 / (2 * beta**2)),
...          linewidth=2, color='g')
>>> plt.show()



### random.hypergeometric

 numpy.random.hypergeometric(ngood, nbad, nsample, size=None)

    Draw samples from a Hypergeometric distribution.

    Samples are drawn from a hypergeometric distribution with specified parameters, ngood (ways to make a good selection), nbad (ways to make a bad selection), and nsample = number of items sampled, which is less than or equal to the sum ngood + nbad.
    
Parameters:	

ngood : int or array_like of ints

    Number of ways to make a good selection. Must be nonnegative.
nbad : int or array_like of ints

    Number of ways to make a bad selection. Must be nonnegative.
nsample : int or array_like of ints

    Number of items sampled. Must be at least 1 and at most ngood + nbad.
size : int or tuple of ints, optional

    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if ngood, nbad, and nsample are all scalars. Otherwise, np.broadcast(ngood, nbad, nsample).size samples are drawn.

Returns:	

out : ndarray or scalar

    Drawn samples from the parameterized hypergeometric distribution.

Consider an urn with black and white marbles in it, ngood of them black and nbad are white. If you draw nsample balls without replacement, then the hypergeometric distribution describes the distribution of black balls in the drawn sample.

Note that this distribution is very similar to the binomial distribution, except that in this case, samples are drawn without replacement, whereas in the Binomial case samples are drawn with replacement (or the sample space is infinite). As the sample space becomes large, this distribution approaches the binomial.

ngood, nbad, nsamp = 100, 2, 10
#number of good, number of bad, and number of samples
>>> s = np.random.hypergeometric(ngood, nbad, nsamp, 1000)
>>> hist(s)
#note that it is very unlikely to grab both bad items

Suppose you have an urn with 15 white and 15 black marbles. If you pull 15 marbles at random, how likely is it that 12 or more of them are one color?
>>>

>>> s = np.random.hypergeometric(15, 15, 15, 100000)
>>> sum(s>=12)/100000. + sum(s<=3)/100000.
#answer = 0.003 ... pretty unlikely!



### random.laplace

 numpy.random.laplace(loc=0.0, scale=1.0, size=None)

    Draw samples from the Laplace or double exponential distribution with specified location (or mean) and scale (decay).

    The Laplace distribution is similar to the Gaussian/normal distribution, but is sharper at the peak and has fatter tails. It represents the difference between two independent, identically distributed exponential random variables.
    Parameters:	

    loc : float or array_like of floats, optional

        The position, \mu, of the distribution peak. Default is 0.
    scale : float or array_like of floats, optional

        \lambda, the exponential decay. Default is 1.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized Laplace distribution.

The first law of Laplace, from 1774, states that the frequency of an error can be expressed as an exponential function of the absolute magnitude of the error, which leads to the Laplace distribution. For many problems in economics and health sciences, this distribution seems to model the data better than the standard Gaussian distribution.

loc, scale = 0., 1.
>>> s = np.random.laplace(loc, scale, 1000)

Display the histogram of the samples, along with the probability density function:
>>>

>>> import matplotlib.pyplot as plt
>>> count, bins, ignored = plt.hist(s, 30, density=True)
>>> x = np.arange(-8., 8., .01)
>>> pdf = np.exp(-abs(x-loc)/scale)/(2.*scale)
>>> plt.plot(x, pdf)

Plot Gaussian for comparison:
>>>

>>> g = (1/(scale * np.sqrt(2 * np.pi)) *
...      np.exp(-(x - loc)**2 / (2 * scale**2)))
>>> plt.plot(x,g)

### random.logistic

 numpy.random.logistic(loc=0.0, scale=1.0, size=None)

    Draw samples from a logistic distribution.

    Samples are drawn from a logistic distribution with specified parameters, loc (location or mean, also median), and scale (>0).
    Parameters:	

    loc : float or array_like of floats, optional

        Parameter of the distribution. Default is 0.
    scale : float or array_like of floats, optional

        Parameter of the distribution. Should be greater than zero. Default is 1.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized logistic distribution.

The Logistic distribution is used in Extreme Value problems where it can act as a mixture of Gumbel distributions, in Epidemiology, and by the World Chess Federation (FIDE) where it is used in the Elo ranking system, assuming the performance of each player is a logistically distributed random variable.

Draw samples from the distribution:
>>>

>>> loc, scale = 10, 1
>>> s = np.random.logistic(loc, scale, 10000)
>>> count, bins, ignored = plt.hist(s, bins=50)

#plot against distribution
>>>

>>> def logist(x, loc, scale):
...     return exp((loc-x)/scale)/(scale*(1+exp((loc-x)/scale))**2)
>>> plt.plot(bins, logist(bins, loc, scale)*count.max()/\
... logist(bins, loc, scale).max())
>>> plt.show()



### random.lognormal

 numpy.random.lognormal(mean=0.0, sigma=1.0, size=None)

    Draw samples from a log-normal distribution.

    Draw samples from a log-normal distribution with specified mean, standard deviation, and array shape. Note that the mean and standard deviation are not the values for the distribution itself, but of the underlying normal distribution it is derived from.
    Parameters:	

    mean : float or array_like of floats, optional

        Mean value of the underlying normal distribution. Default is 0.
    sigma : float or array_like of floats, optional

        Standard deviation of the underlying normal distribution. Should be greater than zero. Default is 1.
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if mean and sigma are both scalars. Otherwise, np.broadcast(mean, sigma).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized log-normal distribution.

A log-normal distribution results if a random variable is the product of a large number of independent, identically-distributed variables in the same way that a normal distribution results if the variable is the sum of a large number of independent, identically-distributed variables.

Draw samples from the distribution:
>>>

>>> mu, sigma = 3., 1. # mean and standard deviation
>>> s = np.random.lognormal(mu, sigma, 1000)

Display the histogram of the samples, along with the probability density function:
>>>

>>> import matplotlib.pyplot as plt
>>> count, bins, ignored = plt.hist(s, 100, density=True, align='mid')

>>>

>>> x = np.linspace(min(bins), max(bins), 10000)
>>> pdf = (np.exp(-(np.log(x) - mu)**2 / (2 * sigma**2))
...        / (x * sigma * np.sqrt(2 * np.pi)))

>>>

>>> plt.plot(x, pdf, linewidth=2, color='r')
>>> plt.axis('tight')
>>> plt.show()

Demonstrate that taking the products of random samples from a uniform distribution can be fit well by a log-normal probability density function.
>>>

>>> # Generate a thousand samples: each is the product of 100 random
>>> # values, drawn from a normal distribution.
>>> b = []
>>> for i in range(1000):
...    a = 10. + np.random.random(100)
...    b.append(np.product(a))

>>>

>>> b = np.array(b) / np.min(b) # scale values to be positive
>>> count, bins, ignored = plt.hist(b, 100, density=True, align='mid')
>>> sigma = np.std(np.log(b))
>>> mu = np.mean(np.log(b))

>>>

>>> x = np.linspace(min(bins), max(bins), 10000)
>>> pdf = (np.exp(-(np.log(x) - mu)**2 / (2 * sigma**2))
...        / (x * sigma * np.sqrt(2 * np.pi)))

>>>

>>> plt.plot(x, pdf, color='r', linewidth=2)
>>> plt.show()

### random.logseries

 numpy.random.logseries(p, size=None)

    Draw samples from a logarithmic series distribution.

    Samples are drawn from a log series distribution with specified shape parameter, 0 < p < 1.
    Parameters:	

    p : float or array_like of floats

        Shape parameter for the distribution. Must be in the range (0, 1).
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if p is a scalar. Otherwise, np.array(p).size samples are drawn.

    Returns:	

    out : ndarray or scalar

        Drawn samples from the parameterized logarithmic series distribution.

The log series distribution is frequently used to represent species richness and occurrence, first proposed by Fisher, Corbet, and Williams in 1943 [2]. It may also be used to model the numbers of occupants seen in cars [3].

Draw samples from the distribution:
>>>

>>> a = .6
>>> s = np.random.logseries(a, 10000)
>>> count, bins, ignored = plt.hist(s)

#plot against distribution
>>>

>>> def logseries(k, p):
...     return -p**k/(k*log(1-p))
>>> plt.plot(bins, logseries(bins, a)*count.max()/
             logseries(bins, a).max(), 'r')
>>> plt.show()



### random.multinomial

 numpy.random.multinomial(n, pvals, size=None)

    Draw samples from a multinomial distribution.

    The multinomial distribution is a multivariate generalisation of the binomial distribution. Take an experiment with one of p possible outcomes. An example of such an experiment is throwing a dice, where the outcome can be 1 through 6. Each sample drawn from the distribution represents n such experiments. Its values, X_i = [X_0, X_1, ..., X_p], represent the number of times the outcome was i.
    Parameters:	

    n : int

        Number of experiments.
    pvals : sequence of floats, length p

        Probabilities of each of the p different outcomes. These should sum to 1 (however, the last element is always assumed to account for the remaining probability, as long as sum(pvals[:-1]) <= 1).
    size : int or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

    Returns:	

    out : ndarray

        The drawn samples, of shape size, if that was provided. If not, the shape is (N,).

        In other words, each entry out[i,j,...,:] is an N-dimensional value drawn from the distribution.

Throw a dice 20 times:
>>>

>>> np.random.multinomial(20, [1/6.]*6, size=1)
array([[4, 1, 7, 5, 2, 1]])

It landed 4 times on 1, once on 2, etc.

Now, throw the dice 20 times, and 20 times again:
>>>

>>> np.random.multinomial(20, [1/6.]*6, size=2)
array([[3, 4, 3, 3, 4, 3],
       [2, 4, 3, 4, 0, 7]])

For the first run, we threw 3 times 1, 4 times 2, etc. For the second, we threw 2 times 1, 4 times 2, etc.

A loaded die is more likely to land on number 6:
>>>

>>> np.random.multinomial(100, [1/7.]*5 + [2/7.])
array([11, 16, 14, 17, 16, 26])

The probability inputs should be normalized. As an implementation detail, the value of the last entry is ignored and assumed to take up any leftover probability mass, but this should not be relied on. A biased coin which has twice as much weight on one side as on the other should be sampled like so:
>>>

>>> np.random.multinomial(100, [1.0 / 3, 2.0 / 3])  # RIGHT
array([38, 62])

not like:
>>>

>>> np.random.multinomial(100, [1.0, 2.0])  # WRONG
array([100,   0])

### random.multivariate_normal

### random.negative_binomial

### random.noncentral_chisquare

### random.noncentral_f

### random.normal

### random.pareto

### random.poisson

### random.power

### random.rayleigh

### random.standard_cauchy

### random.standard_exponential

### random.standard_gamma

### random.standard_normal

### random.standard_t

### random.triangular

### random.uniform

### random.vonmises

### random.wald

### random.weibull

### random.zipf

<a id="RandomGenerator"></a>
## Random generator

### random.RandomState

### random.seed

### random.get_state

### random.set_state

### random.random_sample

### random.standard_normal

In [25]:
np.random.uniform(0.0, 10.0)

8.383057963629755

In [26]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

When using the .arange() and .reshape() together the parameters of the .reshape() method must multiply to equal the parameter of the .arange() method.